# -*- coding: utf-8 -*-
"""Simulacion_potencial_accion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnG1U8HH-zrW92ai83wO6cjS1KsCfDdT
"""

import numpy as np
import matplotlib.pyplot as plt

# =====================
# Parámetros del modelo
# =====================
Cm = 1.0      # Capacitancia de la membrana (µF/cm^2)
gNa = 120   # Conductancia máxima de sodio (mS/cm^2)
gK = 36     # Conductancia máxima de potasio
gL = 0.3      # Conductancia de fuga
ENa = 115.0   # Potencial de reversión de sodio (mV)
EK = -12.0    # Potencial de reversión de potasio (mV)
EL = 10.6     # Potencial de reversión de fuga (mV)

# =====================
# Funciones alfa y beta
# =====================
# Todas reciben el voltaje V en mV
def alpha_m(V): return 0.1 * (25 - V) / (np.exp((25 - V) / 10) - 1)
def beta_m(V):  return 4 * np.exp(-V / 18)
def alpha_h(V): return 0.07 * np.exp(-V / 20)
def beta_h(V):  return 1 / (np.exp((30 - V) / 10) + 1)
def alpha_n(V): return 0.01 * (10 - V) / (np.exp((10 - V) / 10) - 1)
def beta_n(V):  return 0.125 * np.exp(-V / 80)

# =====================
# Corriente externa
# =====================
def I_ext(t):
    """
    Pulso de corriente externa:
    - 10 µA/cm^2 entre 1 y 1.5 ms
    - 0 fuera de ese intervalo
    """
    return 10.0 #if 1.0 < t < 1.5 else 0.0

# =====================
# Ecuaciones de Hodgkin-Huxley
# =====================
def dALLdt(t, Y):
    V, m, h, n = Y  # Y es el vector de estado: [V, m, h, n], voltaje y variables de compuerta
    # Corrientes iónicas
    I_Na = gNa * m**3 * h * (V - ENa)
    I_K = gK * n**4 * (V - EK)
    I_L = gL * (V - EL)

    # Ecuaciones diferenciales
    dVdt = (I_ext(t) - I_Na - I_K - I_L) / Cm
    dmdt = alpha_m(V)*(1-m) - beta_m(V)*m
    dhdt = alpha_h(V)*(1-h) - beta_h(V)*h
    dndt = alpha_n(V)*(1-n) - beta_n(V)*n
    return np.array([dVdt, dmdt, dhdt, dndt])

# =====================
# Integración temporal (RK4)
# =====================
dt = 0.01     # Paso de tiempo (ms)
Tmax = 50     # Tiempo total (ms)
t = np.arange(0, Tmax, dt)

# Condiciones iniciales (equilibrio en reposo)
V0 = 0
m0 = alpha_m(V0) / (alpha_m(V0) + beta_m(V0))
h0 = alpha_h(V0) / (alpha_h(V0) + beta_h(V0))
n0 = alpha_n(V0) / (alpha_n(V0) + beta_n(V0))
Y = np.array([V0, m0, h0, n0])

# Guardar resultados
V_trace = np.zeros_like(t)
V_trace[0] = V0

# =====================
# Bucle de integración RK4
# =====================
for i in range(1, len(t)):
    k1 = dALLdt(t[i-1], Y)
    k2 = dALLdt(t[i-1] + dt/2, Y + dt*k1/2)
    k3 = dALLdt(t[i-1] + dt/2, Y + dt*k2/2)
    k4 = dALLdt(t[i-1] + dt, Y + dt*k3)
    Y += dt * (k1 + 2*k2 + 2*k3 + k4) / 6
    V_trace[i] = Y[0]

# =====================
# Graficar resultados
# =====================
plt.figure(figsize=(8,4))
plt.plot(t, V_trace, color='navy')
plt.title("Modelo de Hodgkin–Huxley (potencial de acción)")
plt.xlabel("Tiempo (ms)")
plt.ylabel("Voltaje (mV)")
plt.grid(True)
plt.show()